FROM resin/%%RESIN_MACHINE_NAME%%-golang

ENV INITSYSTEM on

#RUN apt-get -q update && apt-get install -yq --no-install-recommends \
#    build-essential \
#    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/trinitronx/gobot-led-test
COPY . ./
RUN go get -d -u gobot.io/x/gobot && go get -d -u gobot.io/x/gobot/drivers/gpio && \
    go get -d -u gobot.io/x/gobot/platforms/intel-iot/edison
RUN GOARCH=386 GOOS=linux go build ./main.go

ENTRYPOINT [ "./main" ]
